/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { StudentModel } from "./learnerModel";
import { EvidenceSet, ReasoningContext } from "./evidencePipeline";
import { TeachingDecision } from "./teachingDecisionEngine";
import { LearningPlan } from "./learningPlanner";
import { dbService } from "./db";
import { TimeService } from "./time";

export interface ConfidenceReport {
  knowledgeConfidence: number;
  reasoningConfidence: number;
  evidenceConfidence: number;
  studentConfidence: number;
  citationConfidence: number;
  overallConfidence: number;
}

export interface ResponseLog {
  id: string;
  timestamp: string;
  conceptName: string;
  teachingDecision: TeachingDecision;
  learningPlan: LearningPlan;
  evidenceUsed: EvidenceSet;
  reasoningTrace: string;
  promptVersion: string;
  modelVersion: string;
  responseTimeMs: number;
  tokenUsage: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
  };
  confidence: ConfidenceReport;
  coverageScore: number;
}

export const responseFormatterService = {
  /**
   * Calculates the overall confidence calibration based on multiple sub-confidence scores.
   */
  calibrateConfidence(params: {
    evidence: EvidenceSet;
    reasoning: ReasoningContext;
    studentModel: StudentModel;
  }): ConfidenceReport {
    const { evidence, reasoning, studentModel } = params;

    // 1. Knowledge Confidence: Is the concept present in the Knowledge Base?
    const knowledgeConfidence = evidence.knowledgeNode ? 1.0 : 0.3;

    // 2. Reasoning Confidence: Is there clear textbook definition/context available?
    const reasoningConfidence = (evidence.definition && evidence.definition.length > 20) ? 0.9 : 0.4;

    // 3. Evidence Confidence: Do we have specific slides or sources?
    const evidenceConfidence = (evidence.slideSource && evidence.slideSource.pdf && evidence.slideSource.page) ? 1.0 : 0.5;

    // 4. Student Confidence: What is the student's current profile confidence score for this concept?
    const conceptName = evidence.conceptName;
    const confidenceHistory = studentModel.confidenceHistory[conceptName] || [0.5];
    const studentConfidence = confidenceHistory[confidenceHistory.length - 1] ?? 0.5;

    // 5. Citation Confidence: Are there linked nodes in the knowledge graph?
    const citationConfidence = (evidence.knowledgeGraphLinks && evidence.knowledgeGraphLinks.length > 0) ? 0.95 : 0.6;

    // Overall Calibration Weighted Index:
    const overallConfidence = parseFloat((
      knowledgeConfidence * 0.30 +
      evidenceConfidence * 0.20 +
      reasoningConfidence * 0.20 +
      studentConfidence * 0.15 +
      citationConfidence * 0.15
    ).toFixed(3));

    return {
      knowledgeConfidence,
      reasoningConfidence,
      evidenceConfidence,
      studentConfidence,
      citationConfidence,
      overallConfidence
    };
  },

  /**
   * Computes the semantic coverage score of the retrieved evidence against the query/question context.
   */
  calculateEvidenceCoverage(evidence: EvidenceSet, questionText: string, optionsText: string): number {
    if (!evidence.knowledgeNode) return 0.4; // Low coverage if no KB node exists

    const combinedQuery = `${questionText} ${optionsText}`.toLowerCase();
    const context = `${evidence.definition} ${evidence.textbookContext}`.toLowerCase();

    // Extract significant Vietnamese terms (more than 4 characters to exclude minor particles)
    const words = combinedQuery
      .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"']/g, "")
      .split(/\s+/)
      .filter(w => w.length > 4);

    if (words.length === 0) return 1.0;

    let matchCount = 0;
    words.forEach(word => {
      if (context.includes(word)) {
        matchCount++;
      }
    });

    const ratio = matchCount / words.length;
    // Base score is 60% if node is found, scaled up to 100% based on semantic overlaps
    const coverageScore = parseFloat(Math.min(1.0, 0.6 + ratio * 0.4).toFixed(3));

    return coverageScore;
  },

  /**
   * Parses, structures, beautifies, and formats raw text generated by LLM.
   * Strips unverified expansions if coverage or confidence is low, and appends safe-guard disclaimers.
   */
  formatResponse(params: {
    rawText: string;
    learningPlan: LearningPlan;
    evidence: EvidenceSet;
    reasoning: ReasoningContext;
    studentModel: StudentModel;
    confidence: ConfidenceReport;
    coverageScore: number;
  }): {
    formattedText: string;
    citationsBlock: string;
    warningBox?: string;
  } {
    const { rawText, learningPlan, evidence, reasoning, confidence, coverageScore } = params;
    let formattedText = rawText;

    // 1. Structural Boundaries Check: Hallucination Guard v2
    // If coverage is low, strip any long expansion or prevent false certainties
    if (coverageScore < 0.7) {
      // Look for a section called "AI Expansion" or "Mở rộng" and replace with warning
      const expansionRegex = /(###\s*(?:AI\s*Expansion|Mở rộng|Phân tích mở rộng)[\s\S]*)/i;
      if (expansionRegex.test(formattedText)) {
        formattedText = formattedText.replace(expansionRegex, `### ⚠️ PHÂN TÍCH MỞ RỘNG (AI EXPANSION)
*Tài liệu hiện tại chưa đủ phạm vi phủ để kết luận chuyên sâu về kiến thức mở rộng ngoài giáo trình.*`);
      }
    }

    // 2. Adjust Assertion Level if Overall Confidence is low
    let warningBox = "";
    if (confidence.overallConfidence < 0.6) {
      warningBox = `> ⚠️ **HỆ THỐNG PHÁT CẢNH BÁO KIỂM DUYỆT HỌC THUẬT (LOW CONFIDENCE)**
> Tài liệu môn học hiện tại không đề cập trực tiếp hoặc dữ liệu chứng cứ chưa đồng bộ tối ưu. Các diễn đạt dưới đây mang tính suy luận logic sư phạm bổ trợ kiến thức đại cương, có thể chứa ví dụ do AI tự động tạo để mô phỏng lý thuyết. Người học nên đối chiếu trực tiếp với giáo trình gốc.`;
    }

    // 3. Render Learning Objective & State header beautifully
    const headerBlock = `### 🎯 MỤC TIÊU PHIÊN HỌC (LEARNING OBJECTIVE)
- **Nhiệm vụ trọng tâm**: ${learningPlan.objective}
- **Thang đo năng lực (Bloom Level)**: \`${learningPlan.bloom}\`
- **Phương pháp sư phạm**: \`${learningPlan.strategy}\` (Chiều sâu giải thích: \`${learningPlan.explanationDepth}\`)
${learningPlan.reviewMode ? `- **Lý do ôn tập ngắt quãng**: *${learningPlan.reviewReason}*` : ""}

---
`;

    // 4. Highlight Misconceptions if detected
    let misconceptionBox = "";
    if (reasoning.detectedMisconception.hasMisconception) {
      misconceptionBox = `
> 💡 **HỘP CHỈNH SỬA SAI LẦM (MISCONCEPTION DIAGNOSIS)**
> - **Bẫy tư duy phát hiện**: *${reasoning.detectedMisconception.description}*
> - **Phương án kích hoạt bẫy**: Lựa chọn \`${reasoning.detectedMisconception.triggeringOption?.toUpperCase()}\`
> - **Đơn thuốc sư phạm**: Cần đối chiếu trực tiếp định nghĩa gốc để sửa đổi mô hình tư duy sai lệch.

---
`;
    }

    // Combine blocks
    let finalBody = `${headerBlock}${warningBox ? warningBox + "\n\n" : ""}${misconceptionBox}${formattedText}`;

    // 5. Build High-Quality Citations Block
    const chId = evidence.knowledgeNode?.chapter;
    const chTitle = chId ? (chapterMap.get(chId)?.title || `Chương ${chId}`) : "Chưa rõ";
    const topicId = evidence.knowledgeNode?.topic;
    const topicTitle = topicId ? (topicMap.get(topicId)?.title || topicId) : "Chưa rõ";
    const conceptName = evidence.conceptName;

    // Define evidence type
    let evidenceType = "Knowledge Base";
    if (evidence.slideSource && evidence.slideSource.pdf) {
      evidenceType = "Lecture & Curriculum Slides";
    } else if (evidence.faq && evidence.faq.length > 0) {
      evidenceType = "Exam Blueprint / FAQ Reference";
    }

    // Verification status
    const statusLabel = evidence.knowledgeNode ? "Verified" : "Inference";

    const citationsBlock = `
---
### 📚 BẢN ĐỒ CHỨNG CỨ TRÍCH DẪN ĐỒNG BỘ (EVIDENCE MAP)
- **Học phần đào tạo**: ${dbService.getActiveSubjectName()}
- **Khái niệm gốc**: \`${conceptName}\`
- **Loại hình minh chứng (Evidence Type)**: \`${evidenceType}\`
- **Trạng thái kiểm định (Status)**: 🟢 **${statusLabel}**
- **Nguồn bài giảng chính thức**: ${chTitle} ➔ ${topicTitle}
${evidence.slideSource?.pdf ? `- **Tài liệu tham khảo phụ trợ**: *${evidence.slideSource.pdf}* (Trang/Slide ${evidence.slideSource.page})` : ""}
- **Nội dung giáo trình gốc (Textbook Context)**: 
  > "${evidence.definition}"
- **Lược đồ Knowledge Graph**:
${evidence.knowledgeGraphLinks.map(link => `  * ${link}`).join("\n")}
`;

    return {
      formattedText: finalBody,
      citationsBlock,
      warningBox: warningBox || undefined
    };
  },

  /**
   * Logs a complete structured tracing entry for audit, explainability, and debugging.
   */
  logTracingEntry(entry: Omit<ResponseLog, "id" | "timestamp">): void {
    const activeSubjectId = dbService.getActiveSubjectId();
    const key = `poly_econ_explainability_trace_log_${activeSubjectId}`;
    const raw = localStorage.getItem(key);
    let logs: ResponseLog[] = [];
    if (raw) {
      try {
        logs = JSON.parse(raw);
      } catch {
        logs = [];
      }
    }

    const fullEntry: ResponseLog = {
      ...entry,
      id: `trace-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
      timestamp: TimeService.now().toISOString()
    };

    logs.push(fullEntry);
    // Keep last 100 logs
    localStorage.setItem(key, JSON.stringify(logs.slice(-100)));

    console.log(`[EXPLAINABILITY TRACE] Recorded trace ID: ${fullEntry.id} for Concept: ${fullEntry.conceptName}. Confidence Score: ${fullEntry.confidence.overallConfidence}`);
  },

  getTracingLogs(): ResponseLog[] {
    const activeSubjectId = dbService.getActiveSubjectId();
    const key = `poly_econ_explainability_trace_log_${activeSubjectId}`;
    const raw = localStorage.getItem(key);
    if (!raw) return [];
    try {
      return JSON.parse(raw);
    } catch {
      return [];
    }
  }
};

// Simple mock chapter and topic maps in case they are needed for lookup, importing from db is safer
import { chapterMap, topicMap } from "./db";
